---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
    fabric8.io/iconUrl: "img/icons/vertx.svg"
    fabric8.io/git-branch: "master"
  labels:
    project: "lake"
    provider: "fabric8"
    version: "1.0-SNAPSHOT"
    group: "1340"
  name: "lake"
spec:
  ports:
  - port: 8778
    protocol: "TCP"
    targetPort: 8778
  selector:
    project: "lake"
    provider: "fabric8"
    group: "1340"
  type: "LoadBalancer"
