---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations:
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
      fabric8.io/iconUrl: "img/icons/vertx.svg"
      fabric8.io/git-branch: "master"
    labels:
      project: "lake"
      provider: "fabric8"
      version: "1.0-SNAPSHOT"
      group: "1340"
    name: "lake"
  spec:
    ports:
    - port: 8778
      protocol: "TCP"
      targetPort: 8778
    selector:
      project: "lake"
      provider: "fabric8"
      group: "1340"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    annotations:
      fabric8.io/iconUrl: "img/icons/vertx.svg"
      fabric8.io/git-branch: "master"
      fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=lake&var-version=1.0-SNAPSHOT"
    labels:
      project: "lake"
      provider: "fabric8"
      version: "1.0-SNAPSHOT"
      group: "1340"
    name: "lake"
  spec:
    replicas: 1
    selector:
      project: "lake"
      provider: "fabric8"
      group: "1340"
    template:
      metadata:
        annotations:
          fabric8.io/iconUrl: "img/icons/vertx.svg"
          fabric8.io/git-branch: "master"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=lake&var-version=1.0-SNAPSHOT"
        labels:
          project: "lake"
          provider: "fabric8"
          version: "1.0-SNAPSHOT"
          group: "1340"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "1340/lake:latest"
          imagePullPolicy: "IfNotPresent"
          name: "javaapp"
          ports:
          - containerPort: 9779
            protocol: "TCP"
          - containerPort: 8778
            protocol: "TCP"
          securityContext:
            privileged: false
    triggers:
    - type: "ConfigChange"
kind: "List"
